<?php

use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		// \Illuminate\Support\Facades\DB::table('orders')->insert([
		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 1,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Như Ý",
		// 		'addressSender' => "114 Lê Đại Hành P7 Q11",
		// 		'latitudeSender' => 10.766014,
		// 		'longitudeSender' => 106.650041,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Nguyễn Quốc Bảo",
		// 		'addressReceiver' => "268 Lý Thường Kiệt P14 Q10",
		// 		'latitudeReceiver' => 10.7734259,
		// 		'longitudeReceiver' => 106.658599,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 2,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Cát Tường",
		// 		'addressSender' => "110 Lý Thường Kiệt P7 Q11",
		// 		'latitudeSender' => 10.7599206,
		// 		'longitudeSender' => 106.6590091,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Nguyễn Minh Hiếu",
		// 		'addressReceiver' => "3 Hòa Bình P3 Q11",
		// 		'latitudeReceiver' => 10.7855889,
		// 		'longitudeReceiver' => 106.6588032,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 3,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Trường Thịnh",
		// 		'addressSender' => "132E Cách Mạng Tháng Tám P10 Q3",
		// 		'latitudeSender' => 10.779029,
		// 		'longitudeSender' => 106.67844,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Lê Minh Trung",
		// 		'addressReceiver' => "1 Lữ Gia P14 Q10",
		// 		'latitudeReceiver' => 10.7695746,
		// 		'longitudeReceiver' => 106.6550002,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 4,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Đại Phúc",
		// 		'addressSender' => "339B Lạc Long Quân P5 Q11",
		// 		'latitudeSender' => 10.7708097,
		// 		'longitudeSender' => 106.6430724,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Phạm Hoàng Hải Sơn",
		// 		'addressReceiver' => "291 Điện Biên Phủ P7 Q3",
		// 		'latitudeReceiver' => 10.777948,
		// 		'longitudeReceiver' => 106.683228,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 5,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Hoàng Long",
		// 		'addressSender' => "399 Hồng Bàng P14 Q5",
		// 		'latitudeSender' => 10.7540789,
		// 		'longitudeSender' => 106.6549499,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Hoàng Bách Tùng",
		// 		'addressReceiver' => "227 Nguyễn Văn Cừ P4 Q5",
		// 		'latitudeReceiver' => 10.7624176,
		// 		'longitudeReceiver' => 106.6790028,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 6,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Ánh Dương",
		// 		'addressSender' => "181 Phan Đăng Lưu P1 Q Phú Nhuận",
		// 		'latitudeSender' => 10.8000649,
		// 		'longitudeSender' => 106.6794182,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Nguyễn Đào Anh Khoa",
		// 		'addressReceiver' => "2 Hùng Vương P4 Q5",
		// 		'latitudeReceiver' => 10.7640877,
		// 		'longitudeReceiver' => 106.6767926,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 7,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Quán Bà Ba",
		// 		'addressSender' => "268 Nguyễn Tri Phương Q5",
		// 		'latitudeSender' => 10.7622037,
		// 		'longitudeSender' => 106.6663714,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Nguyễn Hoàng Thanh",
		// 		'addressReceiver' => "120 Lê Đại Hành P11 Q11",
		// 		'latitudeReceiver' => 10.766484,
		// 		'longitudeReceiver' => 106.650077,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 8,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cafe Ong Mật",
		// 		'addressSender' => "497 Hòa Hảo P7 Q10",
		// 		'latitudeSender' => 10.7600173,
		// 		'longitudeSender' => 106.6597775,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Lê Tấn Duy",
		// 		'addressReceiver' => "240 Lý Thường Kiệt P9 Q Tân Bình",
		// 		'latitudeReceiver' => 10.779164,
		// 		'longitudeReceiver' => 106.65291,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 9,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cafe Phú Quý",
		// 		'addressSender' => "84 An Dương Vương P9 Q5",
		// 		'latitudeSender' => 10.7571775,
		// 		'longitudeSender' => 106.668778,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Đỗ Bá Tứ Mỹ",
		// 		'addressReceiver' => "234 Lữ Gia Q10",
		// 		'latitudeReceiver' => 10.7705321,
		// 		'longitudeReceiver' => 106.6547317,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// 	[
		// 		'idOrder' => null,
		// 		'idStore' => 10,
		// 		'billOfLading' => encrypt('LUX' . str_random(12)),
		// 		'nameSender' => "Cửa hàng Hoa Hướng Dương",
		// 		'addressSender' => "55B Phan Đăng Lưu P7 Q Phú Nhuận",
		// 		'latitudeSender' => 10.803132,
		// 		'longitudeSender' => 106.68699,
		// 		'phoneSender' => "0906079807",
		// 		'nameReceiver' => "Nguyễn Quốc Chí",
		// 		'addressReceiver' => "1334 Ba Tháng Hai P16 Q11",
		// 		'latitudeReceiver' => 10.7570961,
		// 		'longitudeReceiver' => 106.6448278,
		// 		'phoneReceiver' => "0931560015",
		// 		'emailReceiver' => null,
		// 		'descriptionOrder' => '',
		// 		'COD' => 0,
		// 		'timeDelivery' => null,
		// 		'distanceShipping' => '',
		// 		'totalWeight' => '',
		// 		'priceService' => '',
		// 		'totalMoney' => '',
		// 		'idServiceType' => 1,
		// 		'idShipper' => 1,
		// 		'idOrderStatus' => 1,
		// 		'created_at' => null,
		// 		'updated_at' => null,
		// 	],

		// ]);
	}
}
